<?xml version="1.0" encoding="UTF-8"?>
<!--
	Copyright 2021 Better Ltd (www.better.care)

	Licensed under the Apache License, Version 2.0 (the "License");
	you may not use this file except in compliance with the License.
	You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

	Unless required by applicable law or agreed to in writing, software
	distributed under the License is distributed on an "AS IS" BASIS,
	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	See the License for the specific language governing permissions and
	limitations under the License.
--><project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>care.better.platform</groupId>
        <artifactId>ehr-common-serialization-polymorphism</artifactId>
        <version>4.3.0</version>
    </parent>

    <artifactId>ehr-common-kotlin-serialization-polymorphisem-generator</artifactId>
    <name>${project.groupId}:${project.artifactId}</name>

    <dependencies>
        <dependency>
            <groupId>care.better.platform</groupId>
            <artifactId>ehr-common-kotlin-serialization-polymorphisem-api</artifactId>
        </dependency>

        <dependency>
            <groupId>com.squareup</groupId>
            <artifactId>kotlinpoet-jvm</artifactId>
        </dependency>

        <dependency>
            <groupId>com.squareup</groupId>
            <artifactId>kotlinpoet-ksp</artifactId>
        </dependency>

        <dependency>
            <groupId>com.google.devtools.ksp</groupId>
            <artifactId>symbol-processing-api</artifactId>
        </dependency>

        <dependency>
            <groupId>org.reflections</groupId>
            <artifactId>reflections</artifactId>
        </dependency>

        <dependency>
            <groupId>org.jetbrains.kotlinx</groupId>
            <artifactId>kotlinx-serialization-core-jvm</artifactId>
        </dependency>
    </dependencies>

</project>