package org.openehr.proc.taskplanning

import javax.xml.bind.annotation.XmlRegistry

/**
 * @author Primoz Delopst
 */

@XmlRegistry
class ObjectFactory {
    fun createTypeDefBoolean(): TypeDefBoolean = TypeDefBoolean()
    fun createTypeDefDate(): TypeDefDate = TypeDefDate()
    fun createTypeDefDateTime(): TypeDefDateTime = TypeDefDateTime()
    fun createTypeDefDuration(): TypeDefDuration = TypeDefDuration()
    fun createTypeDefInteger(): TypeDefInteger = TypeDefInteger()
    fun createTypeDefObject(): TypeDefObject = TypeDefObject()
    fun createTypeDefObjectRef(): TypeDefObjectRef = TypeDefObjectRef()
    fun createTypeDefReal(): TypeDefReal = TypeDefReal()
    fun createTypeDefString(): TypeDefString = TypeDefString()
    fun createTypeDefTerminologyCode(): TypeDefTerminologyCode = TypeDefTerminologyCode()
    fun createTypeDefUri(): TypeDefUri = TypeDefUri()
    fun createTypeDefVoid(): TypeDefVoid = TypeDefVoid()
    fun createTaskEventRecord(): TaskEventRecord = TaskEventRecord()
    fun createTaskNotificationRecord(): TaskNotificationRecord = TaskNotificationRecord()
    fun createTaskPlanEventRecord(): TaskPlanEventRecord = TaskPlanEventRecord()
    fun createTaskPlanExecutionHistory(): TaskPlanExecutionHistory = TaskPlanExecutionHistory()
    fun createAdhocBranch(): AdhocBranch = AdhocBranch()
    fun createAdhocGroup(): AdhocGroup = AdhocGroup()
    fun createApiCall(): ApiCall = ApiCall()
    fun createBooleanContextExpression(): BooleanContextExpression = BooleanContextExpression()
    fun createCalendarEntry(): CalendarEntry = CalendarEntry()
    fun createCalendarEvent(): CalendarEvent = CalendarEvent()
    fun createCallbackNotification(): CallbackNotification = CallbackNotification()
    fun createCallbackWait(): CallbackWait = CallbackWait()
    fun createCaptureDatasetSpec(): CaptureDatasetSpec = CaptureDatasetSpec()
    fun createClockTime(): ClockTime = ClockTime()
    fun createConditionBranch(): ConditionBranch = ConditionBranch()
    fun createConditionGroup(): ConditionGroup = ConditionGroup()
    fun createCustomaryTime(): CustomaryTime = CustomaryTime()
    fun createDatasetCommitGroup(): DatasetCommitGroup = DatasetCommitGroup()
    fun createDecisionBranch(): DecisionBranch = DecisionBranch()
    fun createDecisionGroup(): DecisionGroup = DecisionGroup()
    fun createDefinedAction(): DefinedAction = DefinedAction()
    fun createDispatchableAction(): DispatchableAction = DispatchableAction()
    fun createEventBranch(): EventBranch = EventBranch()
    fun createEventGroup(): EventGroup = EventGroup()
    fun createExecutionRule(): ExecutionRule = ExecutionRule()
    fun createExternalRequest(): ExternalRequest = ExternalRequest()
    fun createHandOff(): HandOff = HandOff()
    fun createManualNotification(): ManualNotification = ManualNotification()
    fun createOrderRef(): OrderRef = OrderRef()
    fun createParameterMapping(): ParameterMapping = ParameterMapping()
    fun createPlanCalendar(): PlanCalendar = PlanCalendar()
    fun createPlanDataContext(): PlanDataContext = PlanDataContext()
    fun createPlanTimeline(): PlanTimeline = PlanTimeline()
    fun createQueryCall(): QueryCall = QueryCall()
    fun createReminder(): Reminder = Reminder()
    fun createResourceParticipation(): ResourceParticipation = ResourceParticipation()
    fun createResumeAction(): ResumeAction = ResumeAction()
    fun createReviewDatasetSpec(): ReviewDatasetSpec = ReviewDatasetSpec()
    fun createStateTrigger(): StateTrigger = StateTrigger()
    fun createSubjectPrecondition(): SubjectPrecondition = SubjectPrecondition()
    fun createSubPlan(): SubPlan = SubPlan()
    fun createSystemNotification(): SystemNotification = SystemNotification()
    fun createSystemRequest(): SystemRequest = SystemRequest()
    fun createTaskCosting(): TaskCosting = TaskCosting()
    fun createTaskParticipation(): TaskParticipation = TaskParticipation()
    fun createTaskPlan(): TaskPlan = TaskPlan()
    fun createTaskRepeat(): TaskRepeat = TaskRepeat()
    fun createTaskTransition(): TaskTransition = TaskTransition()
    fun createTaskWait(): TaskWait = TaskWait()
    fun createTimelineMoment(): TimelineMoment = TimelineMoment()
    fun createTimerEvent(): TimerEvent = TimerEvent()
    fun createTimerWait(): TimerWait = TimerWait()
    fun createWorkPlan(): WorkPlan = WorkPlan()
}